### ISSUE TITLE
Feedback localConnect_actor.js

### ISSUE THREAD

**Issue by uat-iq** [Unitadtechnologystandards/HTML5Lib#1]
Hallo zusammen,

folgendes ist beim Testen von localConnect_actor.js aufgefallen.

**1.) ovk.lc.findOthers-Methode**
Die  Methode setzt derzeit voraus, dass alle Creative-iFrames eines Kombi-Ads im selben "top"-Window der Seite implementiert sind (im Falle einer Wallpaper-Integration wird das i.d.R. auch der Fall sein). Insofern die Creative-iFrames jedoch in weiteren separaten iFrames auf der Seite implementiert werden, schlägt das local-connect fehl, da Creatives bei aktuellem Snippet-Code nicht gefunden werden. 

Zum Beispiel der Fall, wenn 2 kombinierte Inpage-Ads (Billboard über + unter Navi) durch separate asynchrone GPT-Anzeige-Tags auf die Seite geladen werden. Ohne gesondertes Templating verbleiben die Creative-iFrame in den jeweiligen friendly-iFrames der GPT-Tags und sind im window.top durch diese gecovert.

**2.) console.log**
In diesem und auch anderen Snippets sollte aus Kompatibilitätsgründen für console.log vorab eine Feature-Detection bzw. ein eigenes Logging im ovk-Namespace ergänzt werden. Aktuelle Verwendung führt (erneut) zu Problemen im IE11.

LG
Erwin

**Comment by renebaudisch** [comment]
zu 1.): Sicher? Die Methode findOthers wird doch in Zeile 29 rekursiv aufgerufen...

**Comment by renebaudisch** [comment]
findOthers wurde überarbeitet, geht jetzt auch Frames in Frames durch auf die kein Zugriff besteht.
