### ISSUE TITLE
expand.js Beispiele enthalten zuviel Publisher spezifischen Code / kein clip verwenden

### ISSUE THREAD

**Issue by tobiasbaron** [Unitadtechnologystandards/HTML5Lib#4]
Die Beispiele die nachher das Vergrößern und Verkleinern des Werbemittel-Containers/Iframes in der Seite umgesetzen sollten nicht Teil der Code Beispiele sein.

Damit erübrigt sich auch die Frage, ob clip oder eine andere Technik zum vergrößern oder verkleinern der Werbemittel-Containers/Iframes verwendet werden soll.

**Comment by renebaudisch** [comment]
Die aufgeführten Codes sollten lt. Anforderung so aufbereitet sein, dass sie per copy&paste möglichst ohne diese modifizieren zu müssen integrierbar sind, so wurde es an mich herangetragen. Wenn wir keinen Default setzen wäre das nicht möglich.

Dass diese je nach Publisher auch überschrieben werden können wenn gewünscht würde ich natürlich bedenkenlos hinzufügen.
